name-template: 'nightly-$SHORT_SHA'
tag-template: 'nightly-$SHORT_SHA'
categories:
  - title: 'Features'
    labels:
      - feature
      - enhancement
  - title: 'Fixes'
    labels:
      - bug
      - fix
  - title: 'Maintenance'
    labels:
      - chore
      - refactor
change-template: '- $TITLE (#$NUMBER) @${AUTHOR}'
no-changes-template: '- No changes'
template: |
  ## Nightly Build Changes
  $CHANGES
