name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Run tests BEFORE build
      - name: Run tests
        run: flutter test

      # Build APK universal
      - name: Build universal APK
        run: flutter build apk --release

      # Build APK per-ABI
      - name: Build split APKs
        run: flutter build apk --release --split-per-abi

      # Upload artifact untuk download langsung
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/*.apk

      # Build AAB
      - name: Build app bundle (AAB)
        run: flutter build appbundle --release

      # Upload hasil build ke Release dengan tag "nightly"
      - name: Upload Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ github.sha }}
          name: "Nightly Build"
          body: |
            **Nightly Build**
            This is an automatic build from the latest commit on `main`.
            Use at your own risk — features may be unstable.

            Includes:
            - Universal APK
            - Split APKs (arm64, armeabi-v7a, x86_64)
            - AAB (Google Play format)
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_draft:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}