name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Build APK universal
      - name: Build universal APK
        run: flutter build apk --release

      # Build APK per-ABI
      - name: Build split APKs
        run: flutter build apk --release --split-per-abi

      # Build AAB
      - name: Build app bundle (AAB)
        run: flutter build appbundle --release

      # Upload hasil build ke Release dengan tag "nightly"
      - name: Upload Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          name: "Nightly Build"
          body: |
            **Nightly Build**
            This is an automatic build from the latest commit on `main`.
            Use at your own risk — features may be unstable.

            Includes:
            - Universal APK
            - Split APKs (arm64, armeabi-v7a, x86_64)
            - AAB (Google Play format)
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
